[build]
  command   = ""
  publish   = "website"
  base      = ""

[[redirects]]
  from   = "http://danielokonek.art/*"
  to     = "https://danielokonek.art/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "http://www.danielokonek.art/*"
  to     = "https://danielokonek.art/:splat"
  status = 301
  force  = true

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
